/* closed universe with radiation
  Carroll, Lecture Notes on General Relativity, http://ned.ipac.caltech.edu/level5/March01/Carroll3/Carroll8.html ,
  eq. 8.54
 */

load(ctensor);

ct_coords:[t,r,theta,phi];
c : 1; /* square root of Carroll's C', chosen to give big crunch at t=2 */
a : c*sqrt(1-(1-t/c)^2);
k : 1;
lg:matrix([1,0,0,0],
          [0,-a^2*1/(1-k*r^2),0,0],
          [0,0,-a^2*r^2,0],
          [0,0,0,-a^2*r^2*sin(theta)^2]);
load("cm_invariants.mac");
cm_invariants();

cm_do_tests();

cm_print_invariants();
print("The following two limits should be infinite:");
print("limit of R1 as t->0 = ",limit(cm_r1(),t,0));
print("limit of R1 as t->2 = ",limit(cm_r1(),t,2));
