/* Schwarzschild spacetime */

load(ctensor);
ct_coords:[t,r,theta,phi];
lg:matrix([(1-2*m/r),0,0,0],
          [0,-1/(1-2*m/r),0,0],
          [0,0,-r^2,0],
          [0,0,0,-r^2*sin(theta)^2])$
load("cm_invariants.mac");
cm_invariants();

cm_do_tests();

cm_print_invariants();
cm_assert("Schwarzschild metric has W1 approaching infinity as r->0",is(equal(limit(cm_w1(),r,0),infinity)));
cm_assert("Schwarzschild metric has W1=6m^2r^-6",is(equal(trigsimp(ratsimp(cm_w1()-6*m^2*r^-6)),0)));
